version: '3.8'

# Supported models:
# - Intel/Qwen3-Coder-Next-int4-AutoRound
# - cyankiwi/Qwen3-Coder-Next-AWQ-4bit
services:
  Qwen3-Coder-Next:
    image: registry.quuxotic.net/vllm/vllm-openai:v0.22.1
    command: >-
      Intel/Qwen3-Coder-Next-int4-AutoRound
        --enable-auto-tool-choice
        --tool-call-parser qwen3_coder
        --max-model-len 256K
        --served-model-name Qwen3-Coder-Next
        --load-format fastsafetensors
        --gpu-memory-utilization 0.57
        --kv-cache-memory-bytes 28633115307
        --kv-cache-dtype fp8
        --enable-prefix-caching
        --max-num-batched-tokens 8K
        --max-num-seqs 8
        --enable-chunked-prefill
        --moe-backend flashinfer_cutlass
    deploy:
      placement:
        constraints:
          - node.labels.role==secondary
          - node.labels.type==gpu
      resources:
        reservations:
          memory: 68.3G
      restart_policy:
        condition: on-failure
    environment:
      HF_TOKEN:
      VLLM_MARLIN_USE_ATOMIC_ADD: 1
    ulimits:
      memlock: -1
      stack: 67108864
    volumes:
      - /tmp/nvidia-mps:/tmp/nvidia-mps
      - huggingface:/root/.cache/huggingface

volumes:
  huggingface:
