version: '3.8'

services:
  bifrost:
    image: maximhq/bifrost:v1.5.15
    configs:
      - source: bifrost
        target: /app/data/config.json
    depends_on:
      - qdrant
    deploy:
      labels:
        traefik.enable: 'true'
        traefik.http.routers.bifrost.rule: Host(`api.quuxotic.net`)
        traefik.http.services.bifrost.loadbalancer.server.port: 8080
      placement:
        constraints: [node.labels.type==app]
      restart_policy:
        condition: on-failure
    networks:
      - default
      - traefik_proxy
    volumes:
      - bifrost:/app/data

  docling:
    image: ghcr.io/docling-project/docling-serve:v1.26.0
    deploy:
      labels:
        traefik.enable: 'true'
        traefik.http.routers.docling.rule: Host(`docling.quuxotic.net`)
        traefik.http.services.docling.loadbalancer.server.port: 5001
      placement:
        constraints: [node.labels.type==app]
      restart_policy:
        condition: on-failure
    environment:
      DOCLING_SERVE_ENABLE_UI: 'true'
      DOCLING_NUM_THREADS: 32
      DOCLING_SERVE_ENG_LOC_NUM_WORKERS: 32
      DOCLING_SERVE_MAX_SYNC_WAIT: 28800 # 8 hours
      MKL_NUM_THREADS: 32
      OMP_NUM_THREADS: 32

  open-webui:
    image: ghcr.io/open-webui/open-webui:0.9-slim
    depends_on:
      - bifrost
      - docling
      - qdrant
    deploy:
      labels:
        traefik.enable: 'true'
        traefik.http.routers.open-webui.rule: Host(`chat.quuxotic.net`)
        traefik.http.services.open-webui.loadbalancer.server.port: 8080
      placement:
        constraints: [node.labels.type==app]
      restart_policy:
        condition: on-failure
    environment:
      WEBUI_URL: https://chat.quuxotic.net
      DEFAULT_MODEL_METADATA: >-
        {
          "defaultFeatureIds": [
            "web_search"
          ],
        }
      DEFAULT_MODEL_PARAMS: >-
        {
          "function_calling": "native"
        }
      DEFAULT_USER_ROLE: user
      DOCKER: 'True'
      ENABLE_OLLAMA_API: 'False'
      OPENAI_API_BASE_URLS: http://bifrost:8080/openai
      ENABLE_FOLLOW_UP_GENERATION: 'False'
      ENABLE_EVALUATION_ARENA_MODELS: 'False'
      ENABLE_MESSAGE_RATING: 'False'
      VECTOR_DB: qdrant
      QDRANT_URI: http://qdrant:6333
      CONTENT_EXTRACTION_ENGINE: docling
      ENABLE_WEB_SEARCH: 'True'
      WEB_SEARCH_RESULT_COUNT: 5
      WEB_SEARCH_ENGINE: exa
      EXA_API_KEY:
      HF_TOKEN:
    networks:
      - default
      - traefik_proxy
    volumes:
      - open-webui:/app/backend/data

  qdrant:
    image: qdrant/qdrant:v1
    deploy:
      placement:
        constraints: [node.labels.type==app]
      restart_policy:
        condition: on-failure
    volumes:
      - qdrant:/qdrant/storage

networks:
  traefik_proxy:
    external: true

volumes:
  bifrost:
  huggingface:
  open-webui:
  qdrant:

configs:
  bifrost:
    file: ./configs/bifrost/config.json
